### ISSUE TITLE
Gamepads only work when in fullscreen or borderless window mode

### ISSUE THREAD

**Issue by DJRahimAli** [YAL-GameMaker/window_frame#1]
pls fix :(
https://youtu.be/TcjovP5nuHw

**Comment by YellowAfterlife** [comment]
Note that this will not work for DirectInput gamepads and that cannot be fixed without spending upwards to dozen hours investigating DirectInput hooking to force GameMaker to use non-exclusive input mode, which I will not be doing unless someone pays for it (see [here](https://itch.io/post/2690181))
